OS-XXXX need target to build proto.strap cache

diff --git a/tools/build_strap b/tools/build_strap
--- a/tools/build_strap
+++ b/tools/build_strap
@@ -28,16 +28,19 @@
 # true if the user specified non-default compilers.
 #
 
-usage="$0 -a adjunct.tar -d protodir [-f] [-j maxjobs]"
+usage="$0 -a adjunct.tar [-f] [-j maxjobs] [-u | -d protodir]"
 wsroot=$(cd $(dirname $0)/../; pwd)
 pkgin_file="/opt/local/etc/pkgin/repositories.conf"
-manta_base="https://us-east.manta.joyent.com/Joyent_Dev/public/SmartOS/build-cache/proto.strap/"
+manta_host="https://us-east.manta.joyent.com"
+manta_dir="/Joyent_Dev/public/SmartOS/build-cache/proto.strap/"
+manta_base="$manta_host/$manta_dir"
 cache_base="/opt/SmartOS/build-cache/"
 srcdir="$wsroot/projects/illumos-extra"
 adjunct=""
 protodir=""
 max_jobs="128"
 force_build="no"
+upload="no"
 
 function fatal
 {
@@ -71,9 +74,16 @@ function identify_srcsha
 
 function build_strap
 {
-	echo "Building illumos-extra bootstrap"
+	echo "Building illumos-extra bootstrap at $protodir"
 
-	verbose gmake STRAP=strap MAX_JOBS=$max_jobs DESTDIR=$protodir \
+	#
+	# Strip any double slashes. Certain pieces of software simply hate you -
+	# yes, YOU - and get very confused given double slashes. Namely
+	# projects/illumos-extra/make
+	#
+	DESTDIR=$(echo $protodir | sed 's+//*+/+g')
+
+	verbose gmake STRAP=strap MAX_JOBS=$max_jobs DESTDIR=$DESTDIR \
 	    -C $wsroot/projects/illumos-extra install_strap ||
 	    fatal "failed to build install_strap"
 
@@ -130,6 +140,36 @@ function download
 }
 
 #
+# Do a strap build into the cache directory, then upload the tarball into the
+# cache location.
+#
+function upload_strap
+{
+	local cache_dir="$1"
+	local mdir="$2"
+
+	if [[ "$force_build" = "no" ]]; then
+		if mls $mdir >/dev/null 2>&1; then
+			echo "$mdir exists; not building"
+			return
+		fi
+
+		if [[ -d "$cache_dir" ]]; then
+			echo "$cache_dir exists; not building"
+			return
+		fi
+	fi
+
+	mkdir -p "$cache_dir"
+	protodir="$cache_dir"
+
+	build_strap
+
+	gtar -C "$cache_dir" -czf - . | mput -q -p $mdir
+	echo "Uploaded $manta_host/$mdir"
+}
+
+#
 # Populate proto.strap: either we do a local build, or we download and use a
 # cached copy, sym-linking it in.
 #
@@ -141,6 +181,13 @@ function populate_strap
 
 	if [[ -e "$cache_dir" && ! -d "$cache_dir" ]]; then
 		fatal "found weird non-directory $cache_dir"
+	fi
+
+	if [[ "$upload" = "yes" ]]; then
+		local dir="$manta_dir/$pkgsrc_branch/$srcdirsha/proto.strap.tgz.jlevon"
+
+		upload_strap $cache_dir $dir
+		return
 	fi
 
 	#
@@ -173,7 +220,7 @@ function populate_strap
 export PATH=/usr/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin
 set -o pipefail
 
-while getopts "a:d:fhj:" arg; do
+while getopts "a:d:fhj:u" arg; do
 	case $arg in
 	a)
 		adjunct=$OPTARG ;;
@@ -186,6 +233,8 @@ while getopts "a:d:fhj:" arg; do
 		exit 0 ;;
 	j)
 		max_jobs=$OPTARG ;;
+	u)
+		upload="yes" ;;
 	?)
 		echo "$usage" >&2
 		exit 1 ;;
@@ -193,9 +242,14 @@ while getopts "a:d:fhj:" arg; do
 done
 
 [[ -n "$adjunct" ]] || fatal "missing -a argument"
-[[ -n "$protodir" ]] || fatal "missing -d argument"
 [[ -d "$srcdir" ]] || fatal "cannot find illumos-extra in $srcdir"
 [[ -d "$srcdir/.git" ]] || fatal "$srcdir is not a git repo"
+
+if [[ "$upload" = "yes" ]]; then
+	[[ -z "$protodir" ]] || fatal "can't specify -u and -d"
+else
+	[[ -n "$protodir" ]] || fatal "missing -d argument"
+fi
 
 populate_strap $(identify_pkgsrc_branch) $(identify_srcsha)
 
